spring:
    application:
        name: mcp_online_info

    ai:
        mcp:
            server:
                protocol: STREAMABLE
                name: mcp_online_info
                type: sync
server:
    port: 8082