services:
  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    ports:
      - "5432:5432" # Maps the container's port 5432 to the host's port 5432
    volumes:
      - pgdata:/var/lib/postgresql/data # Persists data to a named volume on the host

volumes:
  pgdata: # Defines the named volume
