spring:
    application:
        name: mcp_document
    
    config:
        import: file:.env[.properties]

    datasource:
        url: jdbc:postgresql://localhost:5432/${POSTGRES_DOC_DB}
        username: ${POSTGRES_DOC_USER}
        password: ${POSTGRES_DOC_PASSWORD}
        
    threads:
        virtual:
            enabled: true


    ai:
        openai:
            api-key: ${GROQ_API_KEY}
            base-url: https://api.groq.com/openai
            chat:
                options:
                    model: llama-3.1-8b-instant
        vectorstore:
            pgvector:
                table-name: b3
                dimensions: 2560
        mcp:
            server:
                protocol: STREAMABLE
                name: mcp_document
                type: sync
        embedding:
            transformer:
                tokenizer:
                    uri: classpath:onnx/tokenizer.json
                onnx:
                    gpuDeviceId: 0
                    modelUri: classpath:onnx/model.onnx
                    modelOutputName: "token_embeddings"
server:
  port: 8081

logging:
  level:
    edu:
      tlu:
        mcp_document: DEBUG
    org:
      springframework:
        ai: DEBUG

