spring:
    application:
        name: mcp_document
    
    config:
        import: file:.env[.properties]

    datasource:
        url: jdbc:postgresql://localhost:5433/${POSTGRES_DOC_DB}
        username: ${POSTGRES_DOC_USER}
        password: ${POSTGRES_DOC_PASSWORD}


    ai:
        openai:
            api-key: ${GROQ_API_KEY}
            base-url: https://api.groq.com/openai
            chat:
                options:
                    model: openai/gpt-oss-120b
        vectorstore:
          pgvector:
              dimensions: 2560
        mcp:
            server:
                protocol: STREAMABLE
                name: mcp_document
                type: sync
        embedding:
            transformer:
                tokenizer:
                    uri: classpath:onnx/tokenizer.json
                onnx:
                    modelUri: classpath:onnx/model.onnx
                    modelOutputName: "token_embeddings"
server:
  port: 8081

